{
 "title": "API Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status Code Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (status)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Endpoints by Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, rate(http_request_duration_seconds_sum[5m]) \r\n        / rate(http_request_duration_seconds_count[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time ",
   "type": "timeseries",
   "description": " ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m])\r\n/ rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Distribution (p95 / p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"5..\"}[5m])))\r\n/ sum(rate(http_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}